Class {
	#name : #Gt2InspectorNullExtensions,
	#superclass : #Gt2InspectorProtoModelExtensions,
	#traits : 'TGtUniqueInstance',
	#classTraits : 'TGtUniqueInstance classTrait',
	#category : #'GToolkit-Inspector-! New - Model'
}

{ #category : #notifications }
Gt2InspectorNullExtensions >> objectChangedTo: anObject [
	"do nothing"
]

{ #category : #notifications }
Gt2InspectorNullExtensions >> objectRemoved [
	"do nothing"
]
