Class {
	#name : #Gt2InspectorNullExtension,
	#superclass : #Gt2InspectorProtoModelExtension,
	#traits : 'TGtUniqueInstance',
	#classTraits : 'TGtUniqueInstance classTrait',
	#category : #'GToolkit-Inspector-! New - Model'
}

{ #category : #notifications }
Gt2InspectorNullExtension >> objectChangedTo: anObject [
	"do nothing"
]

{ #category : #notifications }
Gt2InspectorNullExtension >> objectRemoved [
	"do nothing"
]
