Class {
	#name : #GtPagerNullHolder,
	#superclass : #GtPagerProtoHolder,
	#traits : 'TGtUniqueInstance',
	#classTraits : 'TGtUniqueInstance classTrait',
	#category : #'GToolkit-Pager-Strategies'
}

{ #category : #'api - actions' }
GtPagerNullHolder >> close: aPageElement [
	"do nothing"
]

{ #category : #'api - actions' }
GtPagerNullHolder >> maximizePageContent: aContentElement [
	"do nothing"
]

{ #category : #'api - actions' }
GtPagerNullHolder >> select: aGtPagerPageSelectionContext [
	"do nothing"
]

{ #category : #'api - actions' }
GtPagerNullHolder >> smoothScrollToLast [
	"do nothing"
]

{ #category : #'api - actions' }
GtPagerNullHolder >> spawn: aGtPagerPageSelectionContext [
	"do nothing"
]
